

#' Write the result of a query to your user Schema
#'
#' @param input_tbl The sql query generated by dbplyr/dplyr
#' @param con the database connection, defaults to what is set by options()
#' @param table_name The name of the new table you would like to create
#' @param schema your user schema
#' @param db The name of the database, defaults to ohdsi_lab
#' @export
write_to_database <- function(input_tbl,
															con = getOption("con.default.value"),
															schema,
															table_name,
															db = "ohdsi_lab"){
	# SQL query
	sql_query <- glue::glue("SELECT *\n",
													"INTO {db}.{schema}.{tbl_name}\n",
													"FROM (\n",
													dbplyr::sql_render(table_name),
													"\n) AS from_table")

	# run query
	DBI::dbExecute(con, as.character(sql_query))
}
